#! argo submit -p appName="miller" -p shortSha="GENERATE_SHORT_SHA?" -p ciCommitSha="FROM_GH" -p appRepoUrl="FROM_GH" -p gitopsRepoUrl="FROM_GH"
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: testing-123-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: appName
        value: "{{workflow.parameters.appName}}"
      - name: appDir
        value: "/src/{{workflow.parameters.appName}}"
      - name: chartDir
        value: "charts/{{workflow.parameters.appName}}"
      - name: imageTag
        value: "123546"
  serviceAccountName: argo-server
  templates:
    - name: main
      steps:
      - - name: checkout
          templateRef:
            name: cwft-local
            template: git-checkout-with-gitops
            clusterScope: true
            arguments:
              parameters:
                - name: appName
                  value: "{{workflow.parameters.appName}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
                - name: appRepoUrl
                  value: "{{workflow.parameters.appRepoUrl}}"
                - name: gitopsRepoUrl
                  value: "{{workflow.parameters.gitopsRepoUrl}}"
      - - name: publish-container
          templateRef:
            name: cwft-local
            template: docker-build
            clusterScope: true
          arguments:
            artifacts:
            - name: repo-source
              from: "{{steps.checkout.outputs.artifacts.repo-source}}"
            parameters:
            - name: imageTag
              value: "ghcr.io/{{workflow.parameters.githubOwner}}/{{workflow.parameters.appName}}:{{workflow.parameters.ciCommitSha}}"
      - - name: get-initial-chart-version
          templateRef:
            name: cwft-local
            template: helm-get-chart-version
            clusterScope: true
          arguments:
            artifacts:
              - name: repo-source
                from: "{{steps.checkout.outputs.artifacts.repo-source}}"
            parameters:
              - name: appName
                value: "{{workflow.parameters.appName}}"
              - name: chartDir
                value: "{{workflow.parameters.chartDir}}"
      - - name: set-chart-versions
          templateRef:
            name: cwft-local
            template: helm-set-chart-versions
            clusterScope: true
          arguments:
            artifacts:
              - name: repo-source
                from: "{{steps.checkout.outputs.artifacts.repo-source}}"
            parameters:
              - name: appName
                value: "{{workflow.parameters.appName}}"
              - name: chartDir
                value: "{{workflow.parameters.chartDir}}"
              - name: chartVersion
                value: "{{steps.get-initial-chart-version.outputs.result}}-rc.{{workflow.parameters.shortSha}}"
              - name: ciCommitSha
                value: "12354652135"
      # - - name: publish-check-cm # todo if needed
      - - name: publish-helm-chart
          templateRef:
            name: cwft-local
            template: helm-publish-chart
            clusterScope: true
          arguments:
            artifacts:
              - name: repo-source
                from: "{{steps.set-chart-versions.outputs.artifacts.repo-source}}"
            parameters:
              - name: appDir
                value: "{{workflow.parameters.appDir}}"
              - name: chartDir
                value: "{{workflow.parameters.chartDir}}"