# argo submit --generate-name="miller-release-" --serviceaccount=argo-server -p appName="miller" -p branch="main" -p ciCommitSha="1235465213ADSA5ee" -p environment="production" -p gitRepoUrl="https://github.com/your-dns-io/miller" -p shortSha="13ADSA5ee" wf/release.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: appDir
        value: /src/{{workflow.parameters.appName}}
      - name: appName
        value: "{{workflow.parameters.appName}}"
      - name: branch
        value: "{{workflow.parameters.branch}}"
      - name: chartDir
        value: charts/{{workflow.parameters.appName}}
      - name: ciCommitSha
        value: "{{workflow.parameters.ciCommitSha}}"
      - name: environment
        value: "{{workflow.parameters.environment}}"
      - name: fullChartPath
        value: "components/{{workflow.parameters.environment}}/{{workflow.parameters.appName}}/Chart.yaml"
      - name: gitRepoUrl
        value: "{{workflow.parameters.gitRepoUrl}}"
      - name: gitRepoPath
        value: "{{workflow.parameters.gitRepoPath}}"        
      - name: shortSha
        value: "{{workflow.parameters.shortSha}}"
  templates:
    - name: main
      steps:
        - - name: checkout
            templateRef:
              name: cwft-local
              template: git-checkout
              clusterScope: true
            # arguments:
            #   parameters:
            #     - name: appDir
            #       value: "{{workflow.parameters.appDir}}"
            #     - name: branch
            #       value: "{{workflow.parameters.branch}}"
            #     - name: gitRepoUrl
            #       value: "{{workflow.parameters.gitRepoUrl}}"

        - - name: get-initial-chart-version
            templateRef:
              name: cwft-local
              template: helm-get-chart-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: "{{steps.checkout.outputs.artifacts.repo-source}}"
              parameters:
                - name: appDir
                  value: "{{workflow.parameters.appDir}}"
                - name: chartDir
                  value: "{{workflow.parameters.chartDir}}"

        - - name: set-chart-versions
            templateRef:
              name: cwft-local
              template: helm-set-chart-versions
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: "{{steps.checkout.outputs.artifacts.repo-source}}"
              parameters:
                - name: appDir
                  value: "{{workflow.parameters.appDir}}"
                - name: chartDir
                  value: "{{workflow.parameters.chartDir}}"
                - name: chartVersion
                  value: "{{steps.get-initial-chart-version.outputs.result}}"
                - name: ciCommitSha
                  value: "{{workflow.parameters.ciCommitSha}}"

        - - name: publish-helm-chart
            templateRef:
              name: cwft-local
              template: helm-publish-chart
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: "{{steps.set-chart-versions.outputs.artifacts.repo-source}}"
              parameters:
                - name: appDir
                  value: "{{workflow.parameters.appDir}}"
                - name: chartDir
                  value: "{{workflow.parameters.chartDir}}"

        - - name: set-environment-version
            templateRef:
              name: cwft-local
              template: helm-set-environment-version
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: "{{steps.checkout.outputs.artifacts.repo-source}}"
              parameters:
                - name: fullChartPath
                  value: "{{workflow.parameters.fullChartPath}}"
                - name: chartVersion
                  value: "{{steps.get-initial-chart-version.outputs.result}}"
                - name: environment
                  value: "{{workflow.parameters.environment}}"
        - - name: commit-production
            templateRef:
              name: cwft-local
              template: git-commit
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: "{{steps.set-environment-version.outputs.artifacts.repo-source}}"
              parameters:
                - name: appDir
                  value: "/src/gitops"
                - name: appName
                  value: gitops
                - name: commitMessage
                  value: setting {{workflow.parameters.appName}} {{workflow.parameters.environment}} to chart version {{steps.get-initial-chart-version.outputs.result}}-rc.{{workflow.parameters.shortSha}}
        - - name: increment-chart-patch
            templateRef:
              name: cwft-local
              template: helm-increment-chart-patch
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: "{{steps.set-environment-version.outputs.artifacts.repo-source}}"
              parameters:
                - name: appDir
                  value: "{{workflow.parameters.appDir}}"
                - name: chartDir
                  value: "{{workflow.parameters.chartDir}}"
                - name: chartVersion
                  value: "{{steps.get-initial-chart-version.outputs.result}}"
        - - name: commit
            templateRef:
              name: cwft-local
              template: git-commit
              clusterScope: true
            arguments:
              artifacts:
                - name: repo-source
                  from: "{{steps.increment-chart-patch.outputs.artifacts.repo-source}}"
              parameters:
                - name: appName
                  value: "{{workflow.parameters.appName}}"
                - name: appDir
                  value: "/src/{{workflow.parameters.appName}}"
                - name: commitMessage
                  value: setting {{workflow.parameters.appName}} {{workflow.parameters.environment}} to chart version {{steps.get-initial-chart-version.outputs.result}}-rc.{{workflow.parameters.shortSha}}